steps:

  -   name:  'gcr.io/cloud-builders/go'
      args: ['run', 'main.go']

  -   name:  'gcr.io/cloud-builders/docker'
      args:  ['build', '-t', 'gcr.io/nandur-app-backend/nandur', '.']

  -   name:  'gcr.io/cloud-builders/docker'
      args:  ['push', 'gcr.io/nandur-app-backend/nandur']

  -   name:  'gcr.io/cloud-builders/gcloud'
      args:
      -  'run'
      -  'deploy'
      -  'nandur'
      -  '--image=gcr.io/nandur-app-backend/nandur'
      -  '--platform=managed'
      -  '--region=us-central1'
      -  '--allow-unauthenticated'
options:
      logging: NONE
