steps:
  - name: golang:1.21
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
      
  -   name:  'gcr.io/cloud-builders/go'
      args: ['run', 'main.go']

  -   name:  'gcr.io/cloud-builders/docker'
      args:  ['build', '-t', 'gcr.io/nandur/nandur', '.']

  -   name:  'gcr.io/cloud-builders/docker'
      args:  ['push', 'gcr.io/nandur/nandur']

  -   name:  'gcr.io/cloud-builders/gcloud'
      args:
      -  'run'
      -  'deploy'
      -  'nandur'
      -  '--image=gcr.io/nandur/nandur'
      -  '--platform=managed'
      -  '--region=us-central1'
      -  '--allow-unauthenticated'
options:
      logging: NONE
